#!/usr/bin/env bash
#
# Downloads the Filament iOS release and wires it into the Xcode build.
#
# The version is read from gradle/libs.versions.toml so iOS always links the same
# Filament release the Android target depends on. Pass a version explicitly to
# override, e.g. `scripts/setup_filament_ios.sh 1.73.0`.
#
# Produces:
#   iosApp/Vendor/filament/{include,lib}        - headers and static libraries
#   iosApp/Configuration/Filament.local.xcconfig - search paths and -l flags
#
# Both are gitignored; re-run this script after cloning or changing the version.

set -euo pipefail

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly VENDOR_DIR="${REPO_ROOT}/iosApp/Vendor/filament"
readonly XCCONFIG="${REPO_ROOT}/iosApp/Configuration/Filament.local.xcconfig"
readonly VERSION_CATALOG="${REPO_ROOT}/gradle/libs.versions.toml"

resolve_version() {
  if [[ $# -ge 1 && -n "${1}" ]]; then
    printf '%s' "${1}"
    return
  fi
  if [[ ! -f "${VERSION_CATALOG}" ]]; then
    echo "error: ${VERSION_CATALOG} not found; pass the Filament version explicitly." >&2
    exit 1
  fi
  # Matches: filament = "1.73.0"
  local version
  version="$(sed -n 's/^filament[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "${VERSION_CATALOG}" | head -1)"
  if [[ -z "${version}" ]]; then
    echo "error: could not read the 'filament' version from ${VERSION_CATALOG}." >&2
    exit 1
  fi
  printf '%s' "${version}"
}

download_sdk() {
  local version="$1"
  local url="https://github.com/google/filament/releases/download/v${version}/filament-v${version}-ios.tgz"
  local staging
  staging="$(mktemp -d)"
  trap 'rm -rf "${staging}"' RETURN

  echo "==> Downloading Filament v${version} for iOS"
  if ! curl --fail --location --progress-bar "${url}" --output "${staging}/filament-ios.tgz"; then
    echo "error: download failed for ${url}" >&2
    echo "       Check that v${version} publishes an iOS artifact on the Filament releases page." >&2
    exit 1
  fi

  echo "==> Extracting into ${VENDOR_DIR}"
  rm -rf "${VENDOR_DIR}"
  mkdir -p "${VENDOR_DIR}"
  tar -xzf "${staging}/filament-ios.tgz" -C "${VENDOR_DIR}"

  if [[ ! -f "${VENDOR_DIR}/include/filament/Engine.h" ]]; then
    echo "error: extracted archive is missing include/filament/Engine.h." >&2
    exit 1
  fi
}

# Emits `-lfoo` for every static library shipped for the device slice. Deriving the
# list from disk keeps the link line correct when a release adds or drops a library.
library_flags() {
  local lib_dir="${VENDOR_DIR}/lib/iphoneos"
  if [[ ! -d "${lib_dir}" ]]; then
    echo "error: ${lib_dir} not found; unexpected archive layout." >&2
    exit 1
  fi
  local flags=()
  local lib
  for lib in "${lib_dir}"/lib*.a; do
    local name
    name="$(basename "${lib}")"
    name="${name#lib}"
    flags+=("-l${name%.a}")
  done
  if [[ ${#flags[@]} -eq 0 ]]; then
    echo "error: no static libraries found in ${lib_dir}." >&2
    exit 1
  fi
  printf '%s' "${flags[*]}"
}

write_xcconfig() {
  local version="$1"
  local libs
  libs="$(library_flags)"

  echo "==> Writing $(basename "${XCCONFIG}")"
  cat > "${XCCONFIG}" <<EOF
// Generated by scripts/setup_filament_ios.sh for Filament v${version}.
FILAMENT_HEADER_SEARCH_PATHS = "\$(SRCROOT)/Vendor/filament/include"
FILAMENT_LIBRARY_SEARCH_PATHS[sdk=iphoneos*] = "\$(SRCROOT)/Vendor/filament/lib/iphoneos"
FILAMENT_LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*] = "\$(SRCROOT)/Vendor/filament/lib/iphonesimulator"
FILAMENT_OTHER_LDFLAGS = ${libs} -lc++ -framework Metal -framework CoreVideo -framework QuartzCore
EOF
}

main() {
  local version
  version="$(resolve_version "${1:-}")"
  download_sdk "${version}"
  write_xcconfig "${version}"
  echo "==> Filament v${version} is ready. Rebuild the iosApp scheme in Xcode."
}

main "$@"
