#!/usr/bin/env bash
# Downloads the Filament iOS SDK and wires it into the iosApp Xcode build.
#
# Usage:
#   scripts/setup_filament_ios.sh
#
# Environment variables:
#   FILAMENT_VERSION  Filament release to download (default: 1.71.0, matching Android).
#   FILAMENT_SHA256   Optional expected sha256 of the downloaded archive. When set, the
#                     download is verified and the script fails on mismatch.
#
# The SDK is extracted into iosApp/Vendor/filament (git-ignored) and the script generates
# iosApp/Configuration/Filament.local.xcconfig (git-ignored) with the header/library search
# paths and linker flags derived from the static libraries that actually shipped in the
# archive. Without this setup the app still builds and falls back to the static avatar
# preview; with it, VTCFilamentRendererBridge renders the VRM avatar.
#
# Note: the official release archive ships device (arm64) and Intel-simulator (x86_64)
# static libraries. 3D avatar rendering is therefore verified on a physical device build.

set -euo pipefail

FILAMENT_VERSION="${FILAMENT_VERSION:-1.71.0}"
FILAMENT_SHA256="${FILAMENT_SHA256:-}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR_DIR="${REPO_ROOT}/iosApp/Vendor/filament"
XCCONFIG_PATH="${REPO_ROOT}/iosApp/Configuration/Filament.local.xcconfig"
ARCHIVE_URL="https://github.com/google/filament/releases/download/v${FILAMENT_VERSION}/filament-v${FILAMENT_VERSION}-ios.tgz"

# Libraries the renderer cannot work without; everything else found in lib/<arch> is linked too.
REQUIRED_LIBRARIES=(filament backend gltfio_core uberarchive utils)

log() {
    echo "[setup_filament_ios] $1"
}

fail() {
    echo "[setup_filament_ios] ERROR: $1" >&2
    exit 1
}

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

ARCHIVE_PATH="${WORK_DIR}/filament-ios.tgz"
log "Downloading Filament v${FILAMENT_VERSION} for iOS..."
curl --fail --location --silent --show-error --output "${ARCHIVE_PATH}" "${ARCHIVE_URL}" \
    || fail "Download failed: ${ARCHIVE_URL}"

ACTUAL_SHA256="$(shasum -a 256 "${ARCHIVE_PATH}" 2>/dev/null | awk '{print $1}' \
    || sha256sum "${ARCHIVE_PATH}" | awk '{print $1}')"
if [[ -n "${FILAMENT_SHA256}" ]]; then
    [[ "${ACTUAL_SHA256}" == "${FILAMENT_SHA256}" ]] \
        || fail "sha256 mismatch: expected ${FILAMENT_SHA256}, got ${ACTUAL_SHA256}"
    log "sha256 verified."
else
    log "sha256 of the downloaded archive: ${ACTUAL_SHA256}"
    log "(set FILAMENT_SHA256 to pin and verify this value on future runs)"
fi

log "Extracting archive..."
EXTRACT_DIR="${WORK_DIR}/extracted"
mkdir -p "${EXTRACT_DIR}"
tar -xzf "${ARCHIVE_PATH}" -C "${EXTRACT_DIR}"

# Release archives nest the SDK under a top-level "filament" directory; tolerate a flat layout too.
SDK_ROOT="${EXTRACT_DIR}/filament"
if [[ ! -d "${SDK_ROOT}/include" ]]; then
    SDK_ROOT="${EXTRACT_DIR}"
fi
[[ -d "${SDK_ROOT}/include/filament" ]] || fail "Extracted archive is missing include/filament headers."
[[ -d "${SDK_ROOT}/lib" ]] || fail "Extracted archive is missing the lib directory."

ARCH_DIR="${SDK_ROOT}/lib/arm64"
[[ -d "${ARCH_DIR}" ]] || fail "Extracted archive is missing lib/arm64 static libraries."

log "Validating required static libraries..."
LINK_FLAGS=()
for library_path in "${ARCH_DIR}"/lib*.a; do
    [[ -e "${library_path}" ]] || fail "No static libraries found in ${ARCH_DIR}."
    library_file="$(basename "${library_path}")"
    library_name="${library_file#lib}"
    library_name="${library_name%.a}"
    LINK_FLAGS+=("-l${library_name}")
done
for required in "${REQUIRED_LIBRARIES[@]}"; do
    [[ -e "${ARCH_DIR}/lib${required}.a" ]] \
        || fail "Required library lib${required}.a is missing from ${ARCH_DIR}. The v${FILAMENT_VERSION} archive layout may have changed; inspect ${ARCH_DIR} and update REQUIRED_LIBRARIES / the generated xcconfig accordingly."
done

log "Installing SDK into iosApp/Vendor/filament..."
rm -rf "${VENDOR_DIR}"
mkdir -p "${VENDOR_DIR}"
cp -R "${SDK_ROOT}/include" "${VENDOR_DIR}/include"
cp -R "${SDK_ROOT}/lib" "${VENDOR_DIR}/lib"

log "Generating iosApp/Configuration/Filament.local.xcconfig..."
{
    echo "// Generated by scripts/setup_filament_ios.sh for Filament v${FILAMENT_VERSION}."
    echo "// This file is git-ignored; re-run the script to regenerate it."
    echo "FILAMENT_HEADER_SEARCH_PATHS = \"\$(SRCROOT)/Vendor/filament/include\""
    echo "FILAMENT_FRAMEWORK_SEARCH_PATHS ="
    echo "FILAMENT_LIBRARY_SEARCH_PATHS = \"\$(SRCROOT)/Vendor/filament/lib/\$(CURRENT_ARCH)\""
    echo "FILAMENT_OTHER_LDFLAGS = ${LINK_FLAGS[*]} -lc++ -framework Metal -framework CoreVideo -framework QuartzCore"
} > "${XCCONFIG_PATH}"

log "Done. Linked libraries: ${LINK_FLAGS[*]}"
log "Build the iosApp scheme for a physical device (arm64) to render the 3D avatar."
